name: พีรวิชญ์ อ่อนเเก้ว 016  # ใส่ชื่อภาษาไทยและรหัสท้ายของคุณตรงนี้ได้เลยครับ

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ตั้งชื่อขั้นตอนการทำ Checkout เป็นชื่อของคุณด้วยเช่นกันครับ
      - name: Checkout Code by พีรวิชญ์ อ่อนเเก้ว 016
        uses: actions/checkout@v4

      - name: Upload Website Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4