name: Peerawit-Onkaew-016  # ใส่ชื่อ-รหัสไว้ตรงนี้ เพื่อให้อาจารย์เห็นชัดๆ ในหน้า Actions

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ใช้แอกชันมาตรฐานของ GitHub เพื่อให้รันผ่านไม่เอเรอร์
      - name: Checkout Code (Peerawit-Onkaew-016) 
        uses: actions/checkout@v4

      - name: Upload Website Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4